### ISSUE TITLE
Update and replace PyPI package

### ISSUE THREAD

**Issue by chorsley** [rspivak/sftpserver#7]
The sftpserver 0.2 package on PyPI currently doesn't include the support for key auth added a while back. Would it be possible to bump the version number and publish the latest version to PyPI?

**Comment by dahlia** [comment]
+1

**Comment by indera** [comment]
+1

**Comment by dahlia** [comment]
@rspivak When would you release the next version to PyPI?

**Comment by dahlia** [comment]
@rspivak The [last release][1] was on 2011, and it's 5+ years ago.  How about making a new release?

[1]: https://pypi.python.org/pypi/sftpserver/0.2

**Comment by rspivak** [comment]
@dahlia : Done :)

**Comment by dahlia** [comment]
Thanks! 🙏
